name: Firmware linting and building

on:
  pull_request:
    branches: [ main ]
    paths:
      - firmware/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy, rustfmt
            override: true
      - name: Install ESP toolchain
        run: |
          cargo install espup
          espup install --targets esp32
          source $HOME/export-esp.sh
      - name: Run clippy
        working-directory: firmware
        run: cargo clippy -- -D warnings
      - name: Check formatting
        run: cargo fmt -- --files-with-diff --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Install ESP toolchain
        run: |
          cargo install espup
          espup install --targets esp32
          source $HOME/export-esp.sh
      - name: Build
        working-directory: firmware
        run: cargo build
